#!/usr/bin/env python3

import argparse
from core.utils import format_logo
from core import runner

def main():
    parser = argparse.ArgumentParser(
        prog="vigilanteye",
        description="VigilantEye Threat Intelligence CLI",
        add_help=False
    )

    parser.add_argument(
        "indicator",
        nargs="?",
        help="IP, URL, domain, hash gibi bir gösterge"
    )

    parser.add_argument(
        "--help", "-h",
        action="store_true",
        help="Yardım menüsünü göster"
    )

    args = parser.parse_args()

    print(format_logo())

    if args.help or not args.indicator:
        print("""
VigilantEye - Threat Intelligence CLI

Kullanım:
  vigilanteye <ip/domain/hash>
  vigilanteye --help

Örnek:
  vigilanteye 8.8.8.8
  vigilanteye example.com
""")
        return

    # app.py yerine runner.py içindeki function çalışacak
    runner.main(args.indicator)
